// src/components/hr/document-setup-dock.tsx
"use client";

import { useMemo, useRef, useState } from "react";
import type { MouseEvent } from "react";
import { Rnd } from "react-rnd";
import {
  CalendarIcon,
  CheckSquareIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  PenLineIcon,
  Trash2Icon,
  TypeIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "lucide-react";
import { toast } from "sonner";

import { FieldInspector } from "@/components/hr/field-inspector";
import { FieldPalette } from "@/components/hr/field-palette";
import type { FieldToolType } from "@/components/hr/field-palette";
import type { DocumentRecord } from "@/components/hr/types";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { PdfCanvasViewer } from "@/components/pdf/PdfCanvasViewer";
import {
  Field,
  RoleConfig,
  DEFAULT_ROLE_CONFIGS,
  clampField,
  fieldDefaults,
  normalizeRoleConfigs,
  UNASSIGNED_ROLE,
} from "@/lib/field-utils";
import { cn } from "@/lib/utils";

const fieldIconMap = {
  signature: PenLineIcon,
  text: TypeIcon,
  date: CalendarIcon,
  checkbox: CheckSquareIcon,
};

const fieldToneMap = {
  signature: "border-blue-600/80 bg-blue-100/90 text-blue-800 dark:bg-blue-200/90 dark:text-blue-950",
  text: "border-emerald-600/80 bg-emerald-100/90 text-emerald-800 dark:bg-emerald-200/90 dark:text-emerald-950",
  date: "border-amber-600/80 bg-amber-100/90 text-amber-900 dark:bg-amber-200/90 dark:text-amber-950",
  checkbox: "border-violet-600/80 bg-violet-100/90 text-violet-800 dark:bg-violet-200/90 dark:text-violet-950",
};

const fieldLabelToneMap = {
  signature: "bg-blue-600 text-white",
  text: "bg-emerald-600 text-white",
  date: "bg-amber-500 text-black",
  checkbox: "bg-violet-600 text-white",
};

function DocumentSetupDock({
  document,
  onFieldsChange,
  onRoleConfigsChange,
  fullHeight = false,
  isUploading = false,
  uploadProgress = 0,
}: {
  document: DocumentRecord;
  onFieldsChange?: (documentId: string, fields: Field[]) => void;
  onRoleConfigsChange?: (documentId: string, roleConfigs: RoleConfig[]) => void;
  fullHeight?: boolean;
  isUploading?: boolean;
  uploadProgress?: number;
}) {
  const [fields, setFields] = useState<Field[]>(document.fields || []);
  const [roleConfigs, setRoleConfigs] = useState<RoleConfig[]>(
    normalizeRoleConfigs(document.roleConfigs || [...DEFAULT_ROLE_CONFIGS]),
  );
  const [selectedType, setSelectedType] = useState<FieldToolType>("select");
  const [selectedFieldId, setSelectedFieldId] = useState<string | null>(
    document.fields?.[0]?.id || null,
  );
  const [isSaving, setIsSaving] = useState(false);
  const [zoom, setZoom] = useState(72);
  const [pageCount, setPageCount] = useState(0);
  const [currentPage, setCurrentPage] = useState(0);
  const [fitMode, setFitMode] = useState<"width" | "page">("width");
  const viewerRef = useRef<HTMLDivElement>(null);
  const fieldsRef = useRef(fields);

  const selectedField = fields.find((field) => field.id === selectedFieldId);
  const fieldsByPage = useMemo(() => {
    const pageMap = new Map<number, Field[]>();
    for (const field of fields) {
      const pageFields = pageMap.get(field.page);
      if (pageFields) {
        pageFields.push(field);
      } else {
        pageMap.set(field.page, [field]);
      }
    }
    return pageMap;
  }, [fields]);
  const fieldCounts = useMemo(
    () => ({
      signature: fields.filter((field) => field.type === "signature").length,
      text: fields.filter((field) => field.type === "text").length,
      date: fields.filter((field) => field.type === "date").length,
      checkbox: fields.filter((field) => field.type === "checkbox").length,
    }),
    [fields],
  );

  async function addField(page: number, point: { x: number; y: number }) {
    if (isUploading) {
      toast.error("Please wait for the document to finish uploading");
      return;
    }
    if (selectedType === "select") return;

    const defaults = fieldDefaults[selectedType];
    const fieldId =
      typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
        ? crypto.randomUUID()
        : `field-${Date.now()}-${Math.random().toString(16).slice(2)}`;
    const draft = clampField({
      id: fieldId,
      type: selectedType,
      page,
      x: point.x,
      y: point.y,
      width: defaults.width,
      height: defaults.height,
      required: true,
      assigneeRole: UNASSIGNED_ROLE,
    });

    const field = draft as Field;
    const previousSelection = selectedFieldId;
    updateLocalFields([...fieldsRef.current, field]);
    setSelectedFieldId(field.id);
    toast.success(`${selectedType} field placed`);

    try {
      const res = await fetch(`/api/documents/${document.id}`, {
        method: "POST",
        body: JSON.stringify({
          ...draft,
          assigneeRole: draft.assigneeRole,
        }),
      });

      if (!res.ok) {
        const data = (await res.json().catch(() => null)) as
          | { error?: string }
          | null;
        throw new Error(data?.error || "Failed to add field");
      }
    } catch (error) {
      updateLocalFields(
        fieldsRef.current.filter((existingField) => existingField.id !== field.id),
      );
      setSelectedFieldId((current) =>
        current === field.id ? previousSelection : current,
      );
      toast.error(
        error instanceof Error ? error.message : "Failed to add field",
      );
    }
  }

  function updateLocalFields(nextFields: Field[]) {
    fieldsRef.current = nextFields;
    setFields(nextFields);
    onFieldsChange?.(document.id, nextFields);
  }

  async function persistField(fieldId: string, updates: Partial<Field>) {
    const nextFields = fields.map((field) => {
      if (field.id !== fieldId) return field;
      return clampField({
        ...field,
        ...updates,
      }) as Field;
    });
    updateLocalFields(nextFields);
    setSelectedFieldId(fieldId);

    const field = nextFields.find((item) => item.id === fieldId);
    if (!field) return;

    setIsSaving(true);
    await fetch(`/api/documents/${document.id}`, {
      method: "PATCH",
      body: JSON.stringify({
        documentId: document.id,
        fieldId,
        x: field.x,
        y: field.y,
        width: field.width,
        height: field.height,
        required: field.required,
        assigneeRole: field.assigneeRole,
      }),
    });
    setIsSaving(false);
  }

  async function persistRoleConfigs(nextRoleConfigs: RoleConfig[]) {
    const normalizedRoleConfigs = normalizeRoleConfigs(nextRoleConfigs);
    const roleNames = new Set(normalizedRoleConfigs.map((role) => role.name));
    const nextFields = fields.map((field) =>
      !field.assigneeRole || roleNames.has(field.assigneeRole)
        ? field
        : { ...field, assigneeRole: UNASSIGNED_ROLE },
    );

    setRoleConfigs(normalizedRoleConfigs);
    updateLocalFields(nextFields);
    onRoleConfigsChange?.(document.id, normalizedRoleConfigs);

    if (
      selectedFieldId &&
      !roleNames.has(
        nextFields.find((field) => field.id === selectedFieldId)?.assigneeRole || "",
      )
    ) {
      setSelectedFieldId(selectedFieldId);
    }

    setIsSaving(true);
    await Promise.all([
      fetch(`/api/documents/${document.id}`, {
        method: "PUT",
        body: JSON.stringify({
          roleConfigs: normalizedRoleConfigs,
        }),
      }),
      ...nextFields
        .filter((field, index) => field.assigneeRole !== fields[index]?.assigneeRole)
        .map((field) =>
          fetch(`/api/documents/${document.id}`, {
            method: "PATCH",
            body: JSON.stringify({
              documentId: document.id,
              fieldId: field.id,
              x: field.x,
              y: field.y,
              width: field.width,
              height: field.height,
              required: field.required,
              assigneeRole: field.assigneeRole,
            }),
          }),
        ),
    ]);
    setIsSaving(false);
  }

  async function deleteField(fieldId: string) {
    const previousFields = fieldsRef.current;
    const nextFields = previousFields.filter((field) => field.id !== fieldId);
    const previousSelection = selectedFieldId;

    updateLocalFields(nextFields);
    if (selectedFieldId === fieldId) {
      setSelectedFieldId(nextFields[0]?.id || null);
    }
    toast.success("Field removed");

    try {
      const response = await fetch(`/api/documents/${document.id}`, {
        method: "DELETE",
        body: JSON.stringify({ fieldId }),
      });

      if (!response.ok) {
        const data = (await response.json().catch(() => null)) as
          | { error?: string }
          | null;
        throw new Error(data?.error || "Failed to remove field");
      }
    } catch (error) {
      updateLocalFields(previousFields);
      setSelectedFieldId(previousSelection);
      toast.error(
        error instanceof Error ? error.message : "Failed to remove field",
      );
    }
  }

  return (
    <div
      className={cn(
        "grid min-h-0 overflow-hidden border border-border bg-card lg:grid-cols-[220px_minmax(0,1fr)_300px]",
        fullHeight ? "h-full" : "h-130",
      )}
    >
      <aside className="min-h-0 border-b border-border bg-background p-3 lg:border-b-0 lg:border-r">
        <div className="flex h-full flex-col gap-3 sm:flex-row sm:items-end lg:flex-col lg:items-stretch">
          <div className="sm:w-44 lg:w-auto">
            <h3 className="font-mono text-[10px] font-semibold uppercase tracking-widest">
              Add Field
            </h3>
            <p className="mt-1 text-[11px] leading-4 text-muted-foreground">
              Select a field type, then click the PDF to place it.
            </p>
          </div>
          {isUploading ? (
            <div className="mt-4 border border-border bg-card p-4 space-y-3 lg:w-auto sm:w-48">
              <p className="font-mono text-[9px] uppercase tracking-widest text-muted-foreground font-bold">Background Upload</p>
              <div className="flex items-center justify-between text-xs">
                <span className="font-mono text-[10px] text-foreground font-semibold">Uploading PDF...</span>
                <span className="font-mono text-[10px] text-amber-500 font-bold">{uploadProgress}%</span>
              </div>
              <div className="h-1.5 bg-muted overflow-hidden relative">
                <div 
                  className="h-full bg-amber-500 transition-all duration-300"
                  style={{ width: `${uploadProgress}%` }}
                />
              </div>
              <p className="text-[10px] leading-4 text-muted-foreground font-mono">
                Fields and roles can be configured once upload completes in a few seconds.
              </p>
            </div>
          ) : (
            <FieldPalette
              selectedType={selectedType}
              fieldCounts={fieldCounts}
              onSelectType={setSelectedType}
            />
          )}
        </div>
      </aside>

      <section className="grid min-h-107.5 grid-rows-[auto_minmax(0,1fr)_auto] lg:min-h-0">
        <EditorToolbar zoom={zoom} onZoomChange={setZoom} isSaving={isSaving} />
        <div ref={viewerRef} className="sleek-grid min-h-0 overflow-auto bg-zinc-100 p-3 dark:bg-[#121214] sm:p-6">
          <PdfCanvasViewer
            fileUrl={document.fileUrl}
            maxPageWidth={fitMode === "width" ? 1600 : Math.max(320, zoom * 8)}
            className="mx-auto w-full max-w-190"
            pageClassName="relative border-t-8 border-zinc-300 bg-white shadow-xl ring-1 ring-black/10 dark:border-[#3f3f46] dark:shadow-2xl"
            onPageClick={addField}
            onDocumentLoad={(nextPageCount) => setPageCount(nextPageCount)}
            onVisiblePageChange={(pageIndex) => setCurrentPage(pageIndex)}
            renderOverlay={(pageIndex, metrics) =>
              (fieldsByPage.get(pageIndex) || [])
                .map((field, index) => {
                  const Icon = fieldIconMap[field.type];

                  return (
                    <Rnd
                      key={field.id}
                      bounds="parent"
                      cancel=".field-delete-button"
                      size={{
                        width: (field.width / 100) * metrics.width,
                        height: (field.height / 100) * metrics.height,
                      }}
                      position={{
                        x: (field.x / 100) * metrics.width,
                        y: (field.y / 100) * metrics.height,
                      }}
                      onClick={(event: MouseEvent) => {
                        event.stopPropagation();
                        setSelectedFieldId(field.id);
                      }}
                      onMouseDown={(event) => {
                        event.stopPropagation();
                        setSelectedFieldId(field.id);
                      }}
                      onDragStop={(_, data) => {
                        persistField(field.id, {
                          x: (data.x / metrics.width) * 100,
                          y: (data.y / metrics.height) * 100,
                        });
                      }}
                      onResizeStop={(_, __, ref, ___, position) => {
                        persistField(field.id, {
                          x: (position.x / metrics.width) * 100,
                          y: (position.y / metrics.height) * 100,
                          width: (ref.offsetWidth / metrics.width) * 100,
                          height: (ref.offsetHeight / metrics.height) * 100,
                        });
                      }}
                      className={cn(
                        "group flex items-center justify-center border border-dashed shadow-sm backdrop-blur-sm outline outline-0 outline-offset-2 transition-[box-shadow,background-color,outline-color]",
                        fieldToneMap[field.type],
                        selectedFieldId === field.id && "border-solid outline-2 outline-primary ring-2 ring-primary/20",
                      )}
                    >
                      <span
                        className={cn(
                          "pointer-events-none absolute -top-5 left-0 whitespace-nowrap px-1.5 py-0.5 font-mono text-[9px] font-semibold uppercase tracking-wider shadow-sm",
                          fieldLabelToneMap[field.type],
                        )}
                      >
                        {field.type} · {field.assigneeRole || "Unassigned"}
                      </span>
                      <span className="pointer-events-none flex h-full w-full items-center justify-center">
                        <Icon className="h-[45%] max-h-5 min-h-3 w-[45%] max-w-5 min-w-3 stroke-[2.3]" />
                      </span>
                      <span className="absolute -right-2 -top-2 flex size-5 items-center justify-center bg-primary font-mono text-[10px] text-primary-foreground">
                        {index + 1}
                      </span>
                      <button
                        onClick={(event) => {
                          event.stopPropagation();
                          deleteField(field.id);
                        }}
                        onMouseDown={(event) => {
                          event.stopPropagation();
                        }}
                        className="field-delete-button absolute -left-2 -top-2 z-10 hidden size-5 items-center justify-center border border-border bg-background text-destructive shadow-sm group-hover:flex"
                      >
                        <Trash2Icon className="size-3" />
                      </button>
                    </Rnd>
                  );
                })
            }
          />
        </div>
        <div className="flex flex-wrap items-center justify-center gap-2 border-t border-border bg-card px-3 py-2 sm:gap-4 sm:px-4">
          <Button
            variant="ghost"
            size="icon-sm"
            disabled={currentPage <= 0}
            onClick={() => {
              const previousPage = Math.max(0, currentPage - 1);
              viewerRef.current
                ?.querySelector(`[data-pdf-page="${previousPage}"]`)
                ?.scrollIntoView({ behavior: "smooth", block: "start" });
            }}
          >
            <ChevronLeftIcon />
          </Button>
          <span className="border border-border bg-background px-3 py-1 font-mono text-xs">
            {Math.min(currentPage + 1, Math.max(pageCount, 1))}
          </span>
          <span className="font-mono text-xs text-muted-foreground">/ {Math.max(pageCount, 1)}</span>
          <Button
            variant="ghost"
            size="icon-sm"
            disabled={pageCount === 0 || currentPage >= pageCount - 1}
            onClick={() => {
              const nextPage = Math.min(pageCount - 1, currentPage + 1);
              viewerRef.current
                ?.querySelector(`[data-pdf-page="${nextPage}"]`)
                ?.scrollIntoView({ behavior: "smooth", block: "start" });
            }}
          >
            <ChevronRightIcon />
          </Button>
          <Select
            value={fitMode}
            onChange={(event) => setFitMode(event.target.value as "width" | "page")}
            className="h-8 w-32"
          >
            <option value="width">Fit Width</option>
            <option value="page">Fit Page</option>
          </Select>
        </div>
      </section>

      <aside className="flex min-h-[220px] flex-col border-t border-border bg-card p-3 lg:min-h-0 lg:border-l lg:border-t-0">
        <h3 className="mb-4 font-mono text-[10px] font-semibold uppercase tracking-widest">
          Field Inspector
        </h3>
        <FieldInspector
          selectedField={selectedField}
          roleConfigs={roleConfigs}
          onUpdate={persistField}
          onRoleConfigsChange={persistRoleConfigs}
          onDelete={deleteField}
        />
      </aside>
    </div>
  );
}

function EditorToolbar({
  zoom,
  onZoomChange,
  isSaving,
}: {
  zoom: number;
  onZoomChange: (zoom: number) => void;
  isSaving: boolean;
}) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border bg-card px-3 py-2">
      <div className="flex items-center gap-1">
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={() => onZoomChange(Math.max(58, zoom - 6))}
        >
          <ZoomOutIcon />
        </Button>
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={() => onZoomChange(Math.min(104, zoom + 6))}
        >
          <ZoomInIcon />
        </Button>
        <Select
          value={`${zoom}`}
          onChange={(event) => onZoomChange(Number(event.target.value))}
          className="h-7 w-20"
        >
          <option value="58">58%</option>
          <option value="72">72%</option>
          <option value="86">86%</option>
          <option value="100">100%</option>
        </Select>
      </div>
      <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
        {isSaving ? "saving..." : "autosaved"}
      </div>
    </div>
  );
}

export { DocumentSetupDock };

// src/lib/components/docs/document-setup-dock.svelte
<script lang="ts">
	import { toast } from "svelte-sonner";
	import FieldInspector from "$lib/components/docs/field-inspector.svelte";
	import FieldPalette, {
		type FieldToolType,
	} from "$lib/components/docs/field-palette.svelte";
	import SetupField from "$lib/components/docs/setup-field.svelte";
	import type { DocumentRecord } from "$lib/components/docs/types";
	import PdfCanvasViewer from "$lib/components/pdf/PdfCanvasViewer.svelte";
	import Button from "$lib/components/ui/button.svelte";
	import { postFormAction } from "$lib/form-action";
	import {
		type Field,
		type RoleConfig,
		DEFAULT_ROLE_CONFIGS,
		UNASSIGNED_ROLE,
		clampField,
		fieldDefaults,
		normalizeRoleConfigs,
	} from "$lib/field-utils";
	import { cn } from "$lib/utils";

	let {
		document: doc,
		onFieldsChange,
		fullHeight = false,
	}: {
		document: DocumentRecord;
		onFieldsChange?: (documentId: string, fields: Field[]) => void;
		fullHeight?: boolean;
	} = $props();

	function safeRoleConfigs(value: unknown): RoleConfig[] {
		try {
			return normalizeRoleConfigs(value);
		} catch {
			return DEFAULT_ROLE_CONFIGS;
		}
	}

	let fields = $state<Field[]>([]);
	let roleConfigs = $state<RoleConfig[]>(DEFAULT_ROLE_CONFIGS);
	let selectedType = $state<FieldToolType>("select");
	let selectedFieldId = $state<string | null>(null);
	let isSaving = $state(false);
	let zoom = $state(100);
	let pageCount = $state(0);
	let currentPage = $state(0);
	let fitMode = $state<"width" | "page">("width");
	let viewerEl = $state<HTMLDivElement | null>(null);
	let syncedDocumentId = $state("");

	$effect(() => {
		if (syncedDocumentId === doc.id) return;
		syncedDocumentId = doc.id;
		fields = doc.fields || [];
		roleConfigs = safeRoleConfigs(doc.roleConfigs);
		selectedFieldId = doc.fields?.[0]?.id || null;
	});

	const selectedField = $derived(fields.find((field) => field.id === selectedFieldId));
	const fieldsByPage = $derived.by(() => {
		const pageMap = new Map<number, Field[]>();
		for (const field of fields) {
			const pageFields = pageMap.get(field.page);
			if (pageFields) pageFields.push(field);
			else pageMap.set(field.page, [field]);
		}
		return pageMap;
	});
	const fieldCounts = $derived({
		signature: fields.filter((f) => f.type === "signature").length,
		text: fields.filter((f) => f.type === "text").length,
		date: fields.filter((f) => f.type === "date").length,
		checkbox: fields.filter((f) => f.type === "checkbox").length,
	});

	const fieldToneMap = {
		signature: "border-blue-600/80 bg-blue-100/90 text-blue-800",
		text: "border-emerald-600/80 bg-emerald-100/90 text-emerald-800",
		date: "border-amber-600/80 bg-amber-100/90 text-amber-900",
		checkbox: "border-violet-600/80 bg-violet-100/90 text-violet-800",
	} as const;

	const fieldLabelToneMap = {
		signature: "bg-blue-600 text-white",
		text: "bg-emerald-600 text-white",
		date: "bg-amber-500 text-black",
		checkbox: "bg-violet-600 text-white",
	} as const;

	function updateLocalFields(nextFields: Field[]) {
		fields = nextFields;
		onFieldsChange?.(doc.id, nextFields);
	}

	function bumpZoom(delta: number) {
		zoom = Math.min(150, Math.max(50, zoom + delta));
	}

	async function addField(page: number, point: { x: number; y: number }) {
		if (selectedType === "select") return;

		const defaults = fieldDefaults[selectedType];
		const fieldId = crypto.randomUUID();
		const draft = clampField({
			id: fieldId,
			type: selectedType,
			page,
			x: point.x,
			y: point.y,
			width: defaults.width,
			height: defaults.height,
			required: true,
			assigneeRole: UNASSIGNED_ROLE,
		}) as Field;

		const previousSelection = selectedFieldId;
		updateLocalFields([...fields, draft]);
		selectedFieldId = fieldId;

		try {
			await postFormAction(
				"addField",
				{
					id: draft.id,
					type: draft.type,
					page: draft.page,
					x: draft.x,
					y: draft.y,
					width: draft.width,
					height: draft.height,
					required: draft.required,
					assigneeRole: draft.assigneeRole,
				},
				{ apply: false },
			);
		} catch (error) {
			updateLocalFields(fields.filter((f) => f.id !== fieldId));
			selectedFieldId = previousSelection;
			toast.error(error instanceof Error ? error.message : "Failed to add field");
		}
	}

	async function persistField(fieldId: string, updates: Partial<Field>) {
		const nextFields = fields.map((field) =>
			field.id === fieldId ? (clampField({ ...field, ...updates }) as Field) : field,
		);
		updateLocalFields(nextFields);
		selectedFieldId = fieldId;

		const field = nextFields.find((item) => item.id === fieldId);
		if (!field) return;

		isSaving = true;
		try {
			await postFormAction(
				"updateField",
				{
					fieldId,
					x: field.x,
					y: field.y,
					width: field.width,
					height: field.height,
					required: field.required,
					assigneeRole: field.assigneeRole,
				},
				{ apply: false },
			);
		} catch (error) {
			toast.error(error instanceof Error ? error.message : "Failed to update field");
		} finally {
			isSaving = false;
		}
	}

	async function persistRoleConfigs(nextRoleConfigs: RoleConfig[]) {
		const normalized = normalizeRoleConfigs(nextRoleConfigs);
		const roleNames = new Set(normalized.map((role) => role.name));
		const nextFields = fields.map((field) =>
			!field.assigneeRole || roleNames.has(field.assigneeRole)
				? field
				: { ...field, assigneeRole: UNASSIGNED_ROLE },
		);

		roleConfigs = normalized;
		updateLocalFields(nextFields);

		isSaving = true;
		try {
			await postFormAction(
				"saveRoleConfigs",
				{ roleConfigs: JSON.stringify(normalized) },
				{ apply: false },
			);
		} catch (error) {
			toast.error(error instanceof Error ? error.message : "Failed to save roles");
		} finally {
			isSaving = false;
		}
	}

	async function deleteField(fieldId: string) {
		const previousFields = fields;
		const previousSelection = selectedFieldId;
		const nextFields = fields.filter((field) => field.id !== fieldId);
		updateLocalFields(nextFields);
		if (selectedFieldId === fieldId) selectedFieldId = nextFields[0]?.id || null;

		try {
			await postFormAction("deleteField", { fieldId }, { apply: false });
		} catch (error) {
			updateLocalFields(previousFields);
			selectedFieldId = previousSelection;
			toast.error(error instanceof Error ? error.message : "Failed to remove field");
		}
	}
</script>

{#snippet renderOverlay(pageIndex: number, metrics: import("$lib/components/pdf/PdfCanvasViewer.svelte").PageMetrics)}
	{#each fieldsByPage.get(pageIndex) || [] as field, index (field.id)}
		<SetupField
			{field}
			{index}
			{metrics}
			selected={selectedFieldId === field.id}
			toneClass={fieldToneMap[field.type]}
			labelClass={fieldLabelToneMap[field.type]}
			onSelect={() => (selectedFieldId = field.id)}
			onPersist={(updates) => persistField(field.id, updates)}
			onDelete={() => deleteField(field.id)}
		/>
	{/each}
{/snippet}

<div
	class={cn(
		"grid min-h-0 overflow-hidden border border-border bg-card lg:grid-cols-[240px_minmax(0,1fr)_340px]",
		fullHeight ? "h-full" : "h-[32rem]",
	)}
>
	<aside class="min-h-0 border-b border-border bg-background p-3 lg:border-b-0 lg:border-r">
		<div class="flex h-full flex-col gap-3 sm:flex-row sm:items-end lg:flex-col lg:items-stretch">
			<div class="sm:w-44 lg:w-auto">
				<h3 class="font-mono text-[10px] font-semibold">Add Field</h3>
				<p class="mt-1 text-[11px] leading-4 text-muted-foreground">
					Select a field type, then click the PDF to place it.
				</p>
			</div>
			<FieldPalette {selectedType} {fieldCounts} onSelectType={(type) => (selectedType = type)} />
		</div>
	</aside>

	<section class="grid min-h-[27rem] grid-rows-[auto_minmax(0,1fr)_auto] lg:min-h-0">
		<div class="flex flex-wrap items-center justify-between gap-2 border-b border-border bg-card px-3 py-2">
			<div class="flex items-center gap-1">
				<Button variant="ghost" size="sm" class="h-8 w-8 px-0" onclick={() => bumpZoom(-10)}>
					−
				</Button>
				<Button variant="ghost" size="sm" class="h-8 w-8 px-0" onclick={() => bumpZoom(10)}>
					+
				</Button>
				<select
					class="h-8 rounded-md border border-border bg-background px-2 text-xs"
					value={`${zoom}`}
					onchange={(event) => (zoom = Number(event.currentTarget.value))}
				>
					<option value="50">50%</option>
					<option value="75">75%</option>
					<option value="100">100%</option>
					<option value="125">125%</option>
					<option value="150">150%</option>
				</select>
			</div>
			<div class="font-mono text-[10px] text-muted-foreground">
				{isSaving ? "saving..." : "autosaved"}
			</div>
		</div>

		<div bind:this={viewerEl} class="sleek-grid min-h-0 overflow-auto bg-zinc-100 p-3 dark:bg-[#121214]">
			{#if doc.fileUrl}
				<PdfCanvasViewer
					fileUrl={doc.fileUrl}
					{zoom}
					{fitMode}
					class="min-h-full"
					pageClassName="relative border-t-8 border-zinc-300 bg-white ring-1 ring-black/10"
					onPageClick={addField}
					onDocumentLoad={(count) => (pageCount = count)}
					onVisiblePageChange={(pageIndex) => (currentPage = pageIndex)}
					{renderOverlay}
				/>
			{:else}
				<div
					class="mx-auto flex min-h-64 w-full items-center justify-center rounded-lg border border-dashed border-border bg-background px-6 text-center text-sm text-muted-foreground"
				>
					{doc.uploadStatus === "pending_upload"
						? "Document is still uploading. Refresh in a moment."
						: "Document file is not ready yet."}
				</div>
			{/if}
		</div>

		<div class="flex flex-wrap items-center justify-center gap-2 border-t border-border bg-card px-3 py-2">
			<Button
				variant="ghost"
				size="sm"
				class="h-8"
				disabled={currentPage <= 0}
				onclick={() =>
					viewerEl
						?.querySelector(`[data-pdf-page="${Math.max(0, currentPage - 1)}"]`)
						?.scrollIntoView({ behavior: "smooth", block: "start" })}
			>
				Prev
			</Button>
			<span class="flex h-8 items-center border border-border bg-background px-3 font-mono text-xs">
				{Math.min(currentPage + 1, Math.max(pageCount, 1))}
			</span>
			<span class="font-mono text-xs text-muted-foreground">/ {Math.max(pageCount, 1)}</span>
			<Button
				variant="ghost"
				size="sm"
				class="h-8"
				disabled={pageCount === 0 || currentPage >= pageCount - 1}
				onclick={() =>
					viewerEl
						?.querySelector(`[data-pdf-page="${Math.min(pageCount - 1, currentPage + 1)}"]`)
						?.scrollIntoView({ behavior: "smooth", block: "start" })}
			>
				Next
			</Button>
			<select
				class="h-8 rounded-md border border-border bg-background px-2 text-xs"
				value={fitMode}
				onchange={(event) => (fitMode = event.currentTarget.value as "width" | "page")}
			>
				<option value="width">Fit Width</option>
				<option value="page">Fit Page</option>
			</select>
		</div>
	</section>

	<aside class="flex min-h-[220px] flex-col border-t border-border bg-card p-3 lg:min-h-0 lg:border-l lg:border-t-0">
		<h3 class="mb-4 font-mono text-[10px] font-semibold">Field Inspector</h3>
		<FieldInspector
			selectedField={selectedField}
			{roleConfigs}
			onUpdate={persistField}
			onRoleConfigsChange={persistRoleConfigs}
			onDelete={deleteField}
		/>
	</aside>
</div>
