// src/lib/components/signature/SignatureValue.svelte
<script lang="ts">
	import { decodeSignatureVector } from "$lib/field-utils";
	import { cn } from "$lib/utils";

	let {
		value,
		class: className = "",
	}: {
		value?: string;
		class?: string;
	} = $props();

	const vector = $derived(decodeSignatureVector(value));
</script>

{#if vector}
	<svg
		viewBox={vector.viewBox}
		preserveAspectRatio="xMidYMid meet"
		class={cn("block h-full w-full", className)}
		aria-label={vector.name}
	>
		<path d={vector.pathData} fill="currentColor" />
	</svg>
{:else if value?.startsWith("data:image")}
	<img src={value} alt="Signature" class={cn("h-full w-full object-contain", className)} />
{:else}
	<span class={className}>{value}</span>
{/if}

// src/components/signature/SignatureValue.tsx
"use client";

import Image from "next/image";
import { decodeSignatureVector } from "@/lib/field-utils";
import { cn } from "@/lib/utils";

export function SignatureValue({
  value,
  className,
}: {
  value?: string;
  className?: string;
}) {
  const vector = decodeSignatureVector(value);

  if (vector) {
    return (
      <svg
        viewBox={vector.viewBox}
        preserveAspectRatio="xMidYMid meet"
        className={cn("block h-full w-full", className)}
        aria-label={vector.name}
      >
        <path
          d={vector.pathData}
          fill="currentColor"
        />
      </svg>
    );
  }

  if (value?.startsWith("data:image")) {
    return (
      <span className={cn("relative block h-full w-full", className)}>
        <Image src={value} alt="Signature" fill sizes="240px" unoptimized className="object-contain" />
      </span>
    );
  }

  return <span className={className}>{value}</span>;
}
