// src/app/hr/share/[id]/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Copy, Loader2 } from "lucide-react";

type SessionRecord = {
  id: string;
  documentId: string;
  signerName?: string | null;
};

export default function SharePage() {
  const { id } = useParams();
  const [session, setSession] = useState<SessionRecord | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/sessions?sessionId=${id}`)
      .then((res) => res.json())
      .then((data) => {
        setSession(data);
        setIsLoading(false);
      });
  }, [id]);

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard!");
  };

  if (isLoading)
    return (
  <div className="flex h-screen items-center justify-center bg-background">
        <Loader2 className="animate-spin" />
      </div>
    );

  const uniqueUrl =
    typeof window !== "undefined" ? `${window.location.origin}/sign/${id}` : "";
  const publicUrl =
    typeof window !== "undefined"
      ? `${window.location.origin}/sign/p/${session?.documentId}`
      : "";

  return (
    <div className="sleek-grid flex min-h-screen items-center justify-center bg-[var(--paper)] p-8">
      <Card className="w-full max-w-2xl rounded-none border border-border bg-background shadow-2xl">
        <CardContent className="p-12 space-y-10">
          <div className="space-y-2">
            <h1 className="font-mono text-5xl font-semibold uppercase leading-none tracking-tighter">
              Ready to Sign.
            </h1>
            <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
              Secure Document Distribution v2.1
            </p>
          </div>

          <div className="space-y-6">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <Label className="font-mono text-[10px] font-bold uppercase tracking-widest text-primary">
                  Option 1: Unique Link (Specific to {session?.signerName})
                </Label>
                <Badge variant="outline" className="h-4 rounded-none font-mono text-[8px]">
                  ONE-TIME USE
                </Badge>
              </div>
              <div className="group flex items-center justify-between border border-border bg-background p-4 shadow-inner">
                <code className="text-xs font-bold truncate mr-4 text-muted-foreground">
                  {uniqueUrl}
                </code>
                <Button
                  size="icon"
                  variant="ghost"
                  onClick={() => copyToClipboard(uniqueUrl)}
                  className="hover:bg-primary hover:text-primary-foreground h-10 w-10"
                >
                  <Copy className="w-4 h-4" />
                </Button>
              </div>
            </div>

            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <Label className="font-mono text-[10px] font-bold uppercase tracking-widest text-primary">
                  Option 2: Public Link (Send to entire staff)
                </Label>
                <Badge
                  variant="default"
                  className="h-4 rounded-none bg-primary font-mono text-[8px] text-primary-foreground"
                >
                  MULTI-USER
                </Badge>
              </div>
              <div className="group flex items-center justify-between border border-primary/20 bg-primary/5 p-4 shadow-inner">
                <code className="text-xs font-bold truncate mr-4 text-primary">
                  {publicUrl}
                </code>
                <Button
                  size="icon"
                  variant="default"
                  onClick={() => copyToClipboard(publicUrl)}
                  className="h-10 w-10"
                >
                  <Copy className="w-4 h-4" />
                </Button>
              </div>
              <p className="font-mono text-[9px] font-medium uppercase tracking-tight text-muted-foreground">
                * Recommended for high-volume signing (NDAs, Employee Handbooks,
                etc.)
              </p>
            </div>
          </div>

          <div className="flex flex-col space-y-4 pt-4">
            <Button
              className="h-12 w-full"
              onClick={() => (window.location.href = "/hr")}
            >
              Back to Dashboard
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// src/routes/share/[id]/+page.svelte
<script lang="ts">
	import { goto } from "$app/navigation";
	import { page } from "$app/stores";
	import { toast } from "svelte-sonner";
	import Button from "$lib/components/ui/button.svelte";

	type SessionRecord = {
		id: string;
		documentId: string;
		signerName?: string | null;
	};

	let session = $state<SessionRecord | null>(null);
	let isLoading = $state(true);

	const sessionId = $derived($page.params.id);

	$effect(() => {
		const id = sessionId;
		if (!id) return;
		isLoading = true;
		void fetch(`/api/sessions?sessionId=${id}`)
			.then((res) => res.json())
			.then((data) => {
				session = data as SessionRecord;
			})
			.finally(() => {
				isLoading = false;
			});
	});

	const uniqueUrl = $derived(
		typeof window !== "undefined" && session ? `${window.location.origin}/sign/${session.id}` : "",
	);
	const publicUrl = $derived(
		typeof window !== "undefined" && session
			? `${window.location.origin}/sign/p/${session.documentId}`
			: "",
	);

	function copyToClipboard(text: string) {
		void navigator.clipboard.writeText(text);
		toast.success("Copied to clipboard!");
	}
</script>

{#if isLoading}
	<div class="flex h-screen items-center justify-center bg-background">
		<svg class="size-6 animate-spin" viewBox="0 0 24 24" fill="none">
			<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
			<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
		</svg>
	</div>
{:else}
	<div class="sleek-grid flex min-h-screen items-center justify-center bg-(--paper) p-8">
		<div class="w-full max-w-2xl border border-border bg-background p-12">
			<div class="space-y-2">
				<h1 class="font-mono text-5xl font-semibold leading-none">Ready to Sign.</h1>
				<p class="font-mono text-[10px] text-muted-foreground">Secure Document Distribution v2.1</p>
			</div>

			<div class="mt-10 space-y-6">
				<div class="space-y-3">
					<div class="flex items-center justify-between">
						<p class="font-mono text-[10px] font-bold text-primary">
							Option 1: Unique Link (Specific to {session?.signerName || "signer"})
						</p>
						<span class="border border-border px-2 py-0.5 font-mono text-[8px]">ONE-TIME USE</span>
					</div>
					<div class="flex items-center justify-between border border-border bg-background p-4">
						<code class="mr-4 truncate text-xs font-bold text-muted-foreground">{uniqueUrl}</code>
						<Button size="icon" variant="ghost" onclick={() => copyToClipboard(uniqueUrl)}>Copy</Button>
					</div>
				</div>

				<div class="space-y-3">
					<div class="flex items-center justify-between">
						<p class="font-mono text-[10px] font-bold text-primary">Option 2: Public Link (Send to entire staff)</p>
						<span class="bg-primary px-2 py-0.5 font-mono text-[8px] text-primary-foreground">MULTI-USER</span>
					</div>
					<div class="flex items-center justify-between border border-primary/20 bg-primary/5 p-4">
						<code class="mr-4 truncate text-xs font-bold text-primary">{publicUrl}</code>
						<Button size="icon" onclick={() => copyToClipboard(publicUrl)}>Copy</Button>
					</div>
					<p class="font-mono text-[9px] font-medium text-muted-foreground">
						* Recommended for high-volume signing (NDAs, Employee Handbooks, etc.)
					</p>
				</div>
			</div>

			<Button class="mt-10 h-12 w-full" onclick={() => goto("/docs")}>Back to Dashboard</Button>
		</div>
	</div>
{/if}
