// src/routes/(app)/docs/[id]/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { toast } from "svelte-sonner";
  import DocumentDetailPanel from "$lib/components/docs/document-detail-panel.svelte";
  import DocumentReviewPanel from "$lib/components/docs/document-review-panel.svelte";
  import DocumentSetupDock from "$lib/components/docs/document-setup-dock.svelte";
  import type { DocumentRecord } from "$lib/components/docs/types";
  import Button from "$lib/components/ui/button.svelte";
  import Sheet from "$lib/components/ui/sheet.svelte";
  import type { Field, RoleConfig } from "$lib/field-utils";
  import { fetchSigningPackets } from "$lib/packet-cache";
  import { EyeIcon, PaperPlaneTiltIcon } from "phosphor-svelte";

  let { data } = $props();

  let fieldsByDocId = $state<Record<string, Field[]>>({});
  let roleConfigsByDocId = $state<Record<string, RoleConfig[]>>({});
  let reviewOpen = $state(false);
  let shareOpen = $state(false);

  const serverDocument = $derived(
    (data.document as DocumentRecord | null) ?? null,
  );
  const document = $derived.by((): DocumentRecord | null => {
    if (!serverDocument) return null;
    const fields = fieldsByDocId[serverDocument.id];
    const roleConfigs = roleConfigsByDocId[serverDocument.id];
    return fields || roleConfigs
      ? {
          ...serverDocument,
          fields: fields || serverDocument.fields,
          roleConfigs: roleConfigs || serverDocument.roleConfigs,
          signerRoles:
            roleConfigs?.map((role) => role.name) ||
            serverDocument.signerRoles,
        }
      : serverDocument;
  });

  const loadError = $derived(data.error || null);

  const unassignedCount = $derived(
    (document?.fields || []).filter(
      (field) => !String(field.assigneeRole || "").trim(),
    ).length,
  );

  const canShare = $derived(
    Boolean(document?.fields?.length) && unassignedCount === 0,
  );

  const isDocumentUploading = $derived(
    Boolean(document) &&
      (!document?.fileUrl || document.uploadStatus === "pending_upload"),
  );

  $effect(() => {
    const documentId = document?.id;
    if (!documentId) return;
    void fetchSigningPackets(documentId).catch(() => undefined);
  });

  function updateFields(documentId: string, fields: Field[]) {
    fieldsByDocId = { ...fieldsByDocId, [documentId]: fields };
  }

  function updateRoleConfigs(
    documentId: string,
    roleConfigs: RoleConfig[],
  ) {
    roleConfigsByDocId = {
      ...roleConfigsByDocId,
      [documentId]: roleConfigs,
    };
  }

  function openReview() {
    if (!document) return;
    if (isDocumentUploading) {
      toast.error("Wait for the PDF to finish uploading before reviewing");
      return;
    }
    reviewOpen = true;
  }

  function openSharePanel() {
    if (!document) return;
    if (isDocumentUploading) {
      toast.error("Wait for the PDF to finish uploading before sharing");
      return;
    }
    if (unassignedCount > 0) {
      toast.error(
        `Assign all ${unassignedCount} unassigned field${unassignedCount === 1 ? "" : "s"} before sharing`,
      );
      return;
    }
    if (!(document.fields || []).length) {
      toast.error("Add at least one field before sharing");
      return;
    }
    void fetchSigningPackets(document.id).catch(() => undefined);
    shareOpen = true;
  }

  function closeShare() {
    shareOpen = false;
  }

  function closeReview() {
    reviewOpen = false;
  }
</script>

<div class="grid h-full grid-rows-[auto_minmax(0,1fr)] bg-(--paper)">
  <header
    class="flex items-center justify-between gap-3 border-b border-border bg-background px-4 py-2.5"
  >
    <div class="flex min-w-0 items-center gap-3">
      <Button variant="ghost" size="sm" onclick={() => goto("/docs")}
        >← Documents</Button
      >
      <div class="min-w-0">
        <p class="text-[10px] uppercase tracking-wider text-muted-foreground">
          All Documents / Document
        </p>
        <h1 class="truncate text-sm font-semibold">
          {document?.name || "Document"}
        </h1>
      </div>
    </div>
    {#if document}
      <div class="flex shrink-0 items-center gap-2">
        <span
          class="hidden font-mono text-[10px] uppercase tracking-widest text-muted-foreground sm:inline"
        >
          {(document.fields || []).length} fields placed
        </span>
        <Button
          variant="outline"
          size="sm"
          onclick={openReview}
          disabled={isDocumentUploading}
        >
          <EyeIcon class="size-3" />
          Review
        </Button>
        <Button
          size="sm"
          onclick={openSharePanel}
          disabled={isDocumentUploading}
        >
          <PaperPlaneTiltIcon class="size-3" />
          Share Document
        </Button>
      </div>
    {/if}
  </header>

  <div class="min-h-0 p-3 sm:p-4">
    {#if loadError && !document}
      <div
        class="flex h-full flex-col items-center justify-center gap-3 text-sm text-muted-foreground"
      >
        <p>{loadError}</p>
        <Button variant="outline" onclick={() => goto("/docs")}
          >Back to documents</Button
        >
      </div>
    {:else if document}
      {#key document.id}
        <DocumentSetupDock
          {document}
          onFieldsChange={updateFields}
          onRoleConfigsChange={updateRoleConfigs}
          fullHeight
        />
      {/key}
    {:else}
      <div
        class="flex h-full items-center justify-center rounded-lg border border-dashed border-border bg-background text-sm text-muted-foreground"
      >
        Preparing document…
      </div>
    {/if}
  </div>
</div>

<Sheet
  bind:open={shareOpen}
  widthClass="w-[min(100vw,36rem)]"
  hideCloseButton
  labelledBy="share-sheet-title"
>
  <span id="share-sheet-title" class="sr-only">Share document</span>
  {#if document}
    <div class="h-full min-h-0 w-full">
      <DocumentDetailPanel
        {document}
        {canShare}
        onClose={closeShare}
        onEdit={() => {
          closeShare();
        }}
      />
    </div>
  {/if}
</Sheet>

{#if document}
  <Sheet
    bind:open={reviewOpen}
    widthClass="w-[min(100vw,72rem)]"
    hideCloseButton
    labelledBy="review-sheet-title"
  >
    <span id="review-sheet-title" class="sr-only"
      >Review document before sharing</span
    >
    <div class="h-full min-h-0 w-full">
      <DocumentReviewPanel {document} onClose={closeReview} />
    </div>
  </Sheet>
{/if}

// src/app/hr/documents/[id]/page.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowLeftIcon, EyeIcon, SendIcon } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { toast } from "sonner";

import { DocumentDetailPanel } from "@/components/hr/document-detail-panel";
import { DocumentReviewPanel } from "@/components/hr/document-review-panel";
import { DocumentSetupDock } from "@/components/hr/document-setup-dock";
import { HrShell } from "@/components/hr/hr-shell";
import type { DocumentRecord } from "@/components/hr/types";
import { getDocumentCounts, getDocumentStatus } from "@/components/hr/types";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTitle } from "@/components/ui/sheet";
import { Skeleton } from "@/components/ui/skeleton";
import type { Field, RoleConfig } from "@/lib/field-utils";
import { uploadDocument } from "@/lib/upload-document";
import { useCurrentWorkspaceId } from "@/lib/workspace-store";

export default function HRDocumentPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const setupRef = useRef<HTMLDivElement>(null);
  const [documents, setDocuments] = useState<DocumentRecord[]>([]);
  const [document, setDocument] = useState<DocumentRecord | null>(null);
  const [query, setQuery] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [shareOpen, setShareOpen] = useState(false);
  const [reviewOpen, setReviewOpen] = useState(false);
  const [uploadingDocumentName, setUploadingDocumentName] = useState<string | null>(null);
  const workspaceId = useCurrentWorkspaceId();

  function normalizeDocuments(data: unknown) {
    return Array.isArray(data) ? (data as DocumentRecord[]) : [];
  }

  function delay(ms: number) {
    return new Promise((resolve) => window.setTimeout(resolve, ms));
  }

  useEffect(() => {
    let cancelled = false;

    async function fetchWorkspace() {
      setIsLoading(true);
      try {
        const [documentsRes] = await Promise.all([
          fetch(
            workspaceId
              ? `/api/documents?workspaceId=${encodeURIComponent(workspaceId)}`
              : "/api/documents",
          ),
        ]);
        const documentsData = await documentsRes.json();

        let documentData: DocumentRecord | null = null;
        for (let attempt = 0; attempt < 4; attempt += 1) {
          const documentRes = await fetch(`/api/documents/${id}`, {
            cache: "no-store",
          });
          if (documentRes.ok) {
            documentData = await documentRes.json();
            break;
          }

          await delay(180 * (attempt + 1));
        }

        if (cancelled) return;

        setDocuments(normalizeDocuments(documentsData));
        setDocument(documentData);
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    }

    fetchWorkspace().catch(() => {
      if (!cancelled) {
        setDocument(null);
        setIsLoading(false);
      }
    });

    return () => {
      cancelled = true;
    };
  }, [id, workspaceId]);

  const allSessions = documents.flatMap((item) => item.sessions || []);
  const completedCount = allSessions.filter(
    (session) => session.status === "completed",
  ).length;
  const pendingCount = allSessions.filter(
    (session) => session.status === "pending",
  ).length;
  const inProgressCount = documents.filter(
    (item) => getDocumentStatus(item) === "In Progress",
  ).length;

  async function handleUpload(file: File) {
    if (!workspaceId) {
      toast.error("Select or create a workspace before uploading");
      return;
    }

    setUploadingDocumentName(file.name);

    try {
      const data = await uploadDocument(file, workspaceId);
      toast.success("Document uploaded");
      router.push(`/hr/documents/${data.id}`);
    } catch (error) {
      setUploadingDocumentName(null);
      toast.error(error instanceof Error ? error.message : "Upload failed");
    }
  }

  function updateDocumentFields(documentId: string, fields: Field[]) {
    setDocument((current) =>
      current?.id === documentId ? { ...current, fields } : current,
    );
    setDocuments((current) =>
      current.map((item) =>
        item.id === documentId ? { ...item, fields } : item,
      ),
    );
  }

  function updateDocumentRoleConfigs(documentId: string, roleConfigs: RoleConfig[]) {
    setDocument((current) =>
      current?.id === documentId ? { ...current, roleConfigs } : current,
    );
    setDocuments((current) =>
      current.map((item) =>
        item.id === documentId ? { ...item, roleConfigs } : item,
      ),
    );
  }

  function getUnassignedFieldCount(currentDocument?: DocumentRecord | null) {
    return (currentDocument?.fields || []).filter(
      (field) => !String(field.assigneeRole || "").trim(),
    ).length;
  }

  function openSharePanel() {
    const unassignedFieldCount = getUnassignedFieldCount(document);

    if (unassignedFieldCount > 0) {
      toast.error(
        `Assign all ${unassignedFieldCount} unassigned field${unassignedFieldCount === 1 ? "" : "s"} before sharing`,
      );
      setupRef.current?.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
      return;
    }

    setShareOpen(true);
  }

  return (
    <HrShell
      query={query}
      onQueryChange={setQuery}
      onUpload={handleUpload}
      actionOverlay={{
        visible: Boolean(uploadingDocumentName),
        title: "Uploading document",
        documentName: uploadingDocumentName || undefined,
        detail: "Preparing for setup.",
      }}
      headerMode="none"
      pendingCount={pendingCount}
      inProgressCount={inProgressCount}
      completedCount={completedCount}
    >
      <div className="grid min-h-0 overflow-auto xl:overflow-hidden">
        <section className="grid min-h-[760px] grid-rows-[auto_minmax(0,1fr)] overflow-hidden bg-[var(--paper)] xl:min-h-0">
          <div className="border-b border-border bg-background px-4 py-4 sm:px-6">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex min-w-0 items-center gap-3">
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => router.push("/hr/documents")}
                >
                  <ArrowLeftIcon />
                </Button>
                <div className="min-w-0">
                  <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                    All Documents / Document
                  </p>
                  <h1 className="truncate font-mono text-xs font-semibold uppercase tracking-widest">
                    {document?.name || "Loading document..."}
                  </h1>
                </div>
              </div>
              {document ? (
                <div className="flex items-center gap-2">
                  <span className="hidden font-mono text-[10px] uppercase tracking-widest text-muted-foreground sm:inline">
                    {getDocumentCounts(document).fields} fields placed
                  </span>
                  <Button variant="outline" onClick={() => setReviewOpen(true)}>
                    <EyeIcon data-icon="inline-start" />
                    Review
                  </Button>
                  <Button onClick={openSharePanel}>
                    <SendIcon data-icon="inline-start" />
                    Share Document
                  </Button>
                </div>
              ) : null}
            </div>
          </div>

          <div
            ref={setupRef}
            className="min-h-0 overflow-hidden bg-(--paper)] p-4"
          >
            {isLoading ? (
              <div className="grid h-full min-h-0 overflow-hidden border border-border bg-card lg:grid-cols-[150px_minmax(0,1fr)_178px]">
                <div className="border-b p-3 lg:border-b-0 lg:border-r">
                  <Skeleton className="h-9 w-full" />
                </div>
                <div className="min-h-105 p-6">
                  <Skeleton className="mx-auto h-full max-h-160 w-full max-w-130" />
                </div>
                <div className="border-t p-3 lg:border-l lg:border-t-0">
                  <Skeleton className="h-9 w-full" />
                </div>
              </div>
            ) : document ? (
              <DocumentSetupDock
                key={document.id}
                document={document}
                onFieldsChange={updateDocumentFields}
                onRoleConfigsChange={updateDocumentRoleConfigs}
                fullHeight
              />
            ) : (
              <div className="flex h-full items-center justify-center border border-dashed border-border bg-card font-mono text-[11px] uppercase tracking-widest text-muted-foreground">
                Document not found.
              </div>
            )}
          </div>
        </section>

        <Sheet
          open={shareOpen}
          onOpenChange={(nextOpen) => {
            if (!nextOpen) {
              setShareOpen(false);
              return;
            }

            openSharePanel();
          }}
        >
          <SheetContent
            hideCloseButton
            className="left-auto right-0 w-[min(100vw,36rem)] max-w-none translate-x-full border-l border-r-0 p-0 data-[state=open]:translate-x-0"
          >
            <SheetTitle className="sr-only">Share document</SheetTitle>
            <DocumentDetailPanel
              document={document || undefined}
              canShare={getUnassignedFieldCount(document) === 0}
              onClose={() => setShareOpen(false)}
              onEdit={() => {
                setShareOpen(false);
                setupRef.current?.scrollIntoView({
                  behavior: "smooth",
                  block: "start",
                });
              }}
            />
          </SheetContent>
        </Sheet>

        {document ? (
          <Sheet open={reviewOpen} onOpenChange={setReviewOpen}>
            <SheetContent
              hideCloseButton
              className="left-auto right-0 w-[min(100vw,72rem)] max-w-none translate-x-full border-l border-r-0 p-0 data-[state=open]:translate-x-0"
            >
              <SheetTitle className="sr-only">Review document before sharing</SheetTitle>
              <DocumentReviewPanel document={document} onClose={() => setReviewOpen(false)} />
            </SheetContent>
          </Sheet>
        ) : null}
      </div>
    </HrShell>
  );
}
