// src/lib/components/auth/workspace-selector.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { goto } from "$app/navigation";
	import { resolve } from "$app/paths";
	import Button from "$lib/components/ui/button.svelte";
	import { authClient, saveLastWorkspaceId } from "$lib/auth-client";
	import { setCurrentWorkspaceId } from "$lib/workspace-store.svelte";
	import { getLastWorkspaceId } from "./auth-utils";

	let { nextPath }: { nextPath?: string } = $props();

	onMount(() => {
		document.body.classList.add("auth-page");
		return () => document.body.classList.remove("auth-page");
	});

	const sessionStore = authClient.useSession();
	const organizationsStore = authClient.useListOrganizations();

	let busyWorkspaceId = $state("");
	let isContinuingWithoutWorkspace = $state(false);
	let handledAutoSelection = $state(false);

	const session = $derived($sessionStore.data);
	const authOrganizations = $derived($organizationsStore.data);
	const sessionPending = $derived($sessionStore.isPending);
	const workspaces = $derived(
		Array.isArray(authOrganizations) ? authOrganizations : [],
	);
	const lastWorkspaceId = $derived(getLastWorkspaceId(session?.user));
	const preferredWorkspace = $derived(
		workspaces.find((workspace) => workspace.id === lastWorkspaceId) || null,
	);
	const dialogOpen = $derived(
		Boolean(session && authOrganizations !== null && !preferredWorkspace),
	);

	$effect(() => {
		if (sessionPending) return;
		if (!session) {
			const query = nextPath ? `?next=${encodeURIComponent(nextPath)}` : "";
			goto(`${resolve("/signin")}${query}`, { replaceState: true });
			return;
		}
		if (authOrganizations === null) return;
		if (handledAutoSelection) return;

		if (preferredWorkspace) {
			handledAutoSelection = true;
			void selectWorkspace(preferredWorkspace.id, false);
		}
	});

	async function selectWorkspace(
		workspaceId: string,
		shouldPersistSelection: boolean,
	) {
		busyWorkspaceId = workspaceId;
		setCurrentWorkspaceId(workspaceId);
		await authClient.$fetch("/organization/set-active", {
			method: "POST",
			body: { organizationId: workspaceId },
		});
		if (shouldPersistSelection || workspaceId !== lastWorkspaceId) {
			await saveLastWorkspaceId(workspaceId);
		}
		if (nextPath?.startsWith("/accept-invitation/")) {
			const id = nextPath.split("/").pop();
			if (id) {
				await goto(resolve("/accept-invitation/[id]", { id }), { replaceState: true });
				return;
			}
		}

		await goto(resolve("/docs"), { replaceState: true });
	}

	async function continueWithoutWorkspace() {
		isContinuingWithoutWorkspace = true;
		await saveLastWorkspaceId(null);

		if (nextPath?.startsWith("/accept-invitation/")) {
			const id = nextPath.split("/").pop();
			if (id) {
				await goto(resolve("/accept-invitation/[id]", { id }), { replaceState: true });
				return;
			}
		}

		await goto(resolve("/docs"), { replaceState: true });
	}
</script>

<main class="flex min-h-svh items-center justify-center bg-(--paper) px-4 py-8">
	{#if dialogOpen}
		<div
			class="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-4 backdrop-blur-[2px]"
			role="dialog"
			aria-modal="true"
			aria-labelledby="workspace-dialog-title"
		>
			<div class="w-full max-w-lg border border-border bg-popover">
				<div class="border-b border-border px-5 py-4">
					<p
						class="font-mono text-[10px] font-semibold uppercase tracking-widest text-muted-foreground"
					>
						Workspace Access
					</p>
					<h2 id="workspace-dialog-title" class="mt-2 text-base font-medium">
						Choose the workspace you want to open
					</h2>
					<p class="mt-2 text-sm text-muted-foreground">
						We'll remember this workspace and log you into it automatically the
						next time you sign in.
					</p>
				</div>

				<div class="space-y-3 px-5 py-4">
					{#if workspaces.length === 0}
						<div class="border border-dashed border-border bg-background p-4">
							<div class="mb-2 flex items-center gap-1">
								<svg class="size-4" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
									<path d="M3 21V9l9-6 9 6v12H3zm2-2h14V10.2l-7-4.67-7 4.67V19zm4-2h6v-6H9v6z" />
								</svg>
								<p class="text-sm font-medium text-foreground">No workspaces yet</p>
							</div>
							<p class="text-xs text-muted-foreground">
								Your account signed in successfully. Continue to your dashboard and
								create a workspace from the account menu.
							</p>

							<Button
								class="mt-3 w-full gap-2"
								onclick={continueWithoutWorkspace}
								disabled={isContinuingWithoutWorkspace}
								loading={isContinuingWithoutWorkspace}
							>
								Continue
								<svg class="size-4" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
									<path d="M13 5l7 7-7 7v-4H4v-6h9V5z" />
								</svg>
							</Button>
						</div>
					{:else}
						{#each workspaces as workspace (workspace.id)}
							<button
								type="button"
								onclick={() => selectWorkspace(workspace.id, true)}
								disabled={busyWorkspaceId === workspace.id}
								class="flex w-full items-center justify-between gap-3 border border-border bg-background px-4 py-3 text-left transition-colors hover:bg-muted disabled:pointer-events-none disabled:opacity-60"
							>
								<div class="min-w-0">
									<p class="truncate text-sm font-medium text-foreground">
										{workspace.name}
									</p>
									<p
										class="truncate font-mono text-[10px] uppercase tracking-widest text-muted-foreground"
									>
										{workspace.slug}
									</p>
								</div>

								{#if busyWorkspaceId === workspace.id}
									<svg
										class="size-4 animate-spin text-foreground"
										viewBox="0 0 24 24"
										fill="none"
										aria-hidden="true"
									>
										<circle
											class="opacity-25"
											cx="12"
											cy="12"
											r="10"
											stroke="currentColor"
											stroke-width="4"
										/>
										<path
											class="opacity-75"
											fill="currentColor"
											d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
										/>
									</svg>
								{:else}
									<svg
										class="size-4 text-muted-foreground"
										viewBox="0 0 24 24"
										fill="currentColor"
										aria-hidden="true"
									>
										<path d="M13 5l7 7-7 7v-4H4v-6h9V5z" />
									</svg>
								{/if}
							</button>
						{/each}
					{/if}
				</div>
			</div>
		</div>
	{:else}
		<div class="flex items-center gap-3 text-sm text-muted-foreground">
			<svg
				class="size-4 animate-spin text-foreground"
				viewBox="0 0 24 24"
				fill="none"
				aria-hidden="true"
			>
				<circle
					class="opacity-25"
					cx="12"
					cy="12"
					r="10"
					stroke="currentColor"
					stroke-width="4"
				/>
				<path
					class="opacity-75"
					fill="currentColor"
					d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
				/>
			</svg>
			Preparing your workspace access...
		</div>
	{/if}
</main>

// src/components/auth/workspace-selector.tsx
"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { ArrowRightIcon, Building2Icon, LoaderCircleIcon } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { authClient, saveLastWorkspaceId } from "@/lib/auth-client";
import { setCurrentWorkspaceId } from "@/lib/workspace-store";

type WorkspaceSelectorProps = {
  nextPath?: string;
};

type WorkspaceSummary = {
  id: string;
  name: string;
  slug: string;
};

function WorkspaceSelector({ nextPath }: WorkspaceSelectorProps) {
  const router = useRouter();
  const { data: session, isPending: sessionPending } = authClient.useSession();
  const { data: authOrganizations } = authClient.useListOrganizations();
  const workspaces = React.useMemo(
    () => (Array.isArray(authOrganizations) ? authOrganizations : []),
    [authOrganizations],
  );
  const [showFallbackDialog, setShowFallbackDialog] = React.useState(false);
  const [busyWorkspaceId, setBusyWorkspaceId] = React.useState("");
  const [isContinuingWithoutWorkspace, setIsContinuingWithoutWorkspace] =
    React.useState(false);
  const handledAutoSelectionRef = React.useRef(false);

  const lastWorkspaceId = getLastWorkspaceId(session?.user);
  const preferredWorkspace = React.useMemo(
    () =>
      workspaces.find((workspace) => workspace.id === lastWorkspaceId) || null,
    [lastWorkspaceId, workspaces],
  );
  const dialogOpen =
    showFallbackDialog ||
    Boolean(session && authOrganizations && !preferredWorkspace);

  const runAutoSelection = React.useEffectEvent((workspaceId: string) => {
    void selectWorkspace(workspaceId, false);
  });

  React.useEffect(() => {
    if (sessionPending) return;
    if (!session) {
      router.replace(appendNextPath("/signin", nextPath));
      return;
    }
    if (!authOrganizations) return;
    if (handledAutoSelectionRef.current) return;

    if (preferredWorkspace) {
      handledAutoSelectionRef.current = true;
      runAutoSelection(preferredWorkspace.id);
    }
  }, [
    authOrganizations,
    nextPath,
    preferredWorkspace,
    session,
    sessionPending,
    router,
  ]);

  async function selectWorkspace(
    workspaceId: string,
    shouldPersistSelection: boolean,
  ) {
    try {
      setBusyWorkspaceId(workspaceId);
      setCurrentWorkspaceId(workspaceId);
      await authClient.$fetch("/organization/set-active", {
        method: "POST",
        body: { organizationId: workspaceId },
      });
      if (shouldPersistSelection || workspaceId !== lastWorkspaceId) {
        await saveLastWorkspaceId(workspaceId);
      }
      router.replace(nextPath || "/hr/documents");
    } catch {
      toast.error("Unable to open that workspace");
      setBusyWorkspaceId("");
      handledAutoSelectionRef.current = false;
      setShowFallbackDialog(true);
    }
  }

  async function continueWithoutWorkspace() {
    try {
      setIsContinuingWithoutWorkspace(true);
      await saveLastWorkspaceId(null);
      router.replace(nextPath || "/hr/documents");
    } catch {
      toast.error("Unable to continue right now");
      setIsContinuingWithoutWorkspace(false);
    }
  }

  return (
    <main className="flex min-h-svh items-center justify-center bg-[var(--paper)] px-4 py-8">
      <Dialog
        open={dialogOpen}
        onOpenChange={(open) => {
          if (busyWorkspaceId || isContinuingWithoutWorkspace) return;
          setShowFallbackDialog(open);
        }}
      >
        <DialogContent showCloseButton={false} className="max-w-lg p-0">
          <DialogHeader className="border-b border-border px-5 py-4">
            <p className="font-mono text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
              Workspace Access
            </p>
            <DialogTitle>Choose the workspace you want to open</DialogTitle>
            <DialogDescription>
              We&apos;ll remember this workspace and log you into it
              automatically the next time you sign in.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-3 px-5 py-4">
            {workspaces.length === 0 ? (
              <div className="border border-dashed border-border bg-background p-4">
                <div className="flex items-center gap-1 mb-2">
                  <Building2Icon className="size-4" />
                  <p className="text-sm font-medium text-foreground">
                    No workspaces yet
                  </p>
                </div>
                <p className="text-xs text-muted-foreground">
                  Your account signed in successfully. Continue to your
                  dashboard and create a workspace from the account menu.
                </p>

                <Button
                  className="w-full gap-2 mt-3"
                  onClick={continueWithoutWorkspace}
                  disabled={isContinuingWithoutWorkspace}
                >
                  {isContinuingWithoutWorkspace ? (
                    <LoaderCircleIcon className="animate-spin" />
                  ) : null}
                  Continue
                  <ArrowRightIcon data-icon="inline-end" />
                </Button>
              </div>
            ) : (
              workspaces.map((workspace) => (
                <WorkspaceOption
                  key={workspace.id}
                  workspace={workspace}
                  isBusy={busyWorkspaceId === workspace.id}
                  onSelect={() => selectWorkspace(workspace.id, true)}
                />
              ))
            )}
          </div>
        </DialogContent>
      </Dialog>

      {!dialogOpen ? (
        <div className="flex items-center gap-3 border border-border bg-background px-4 py-3 text-sm text-muted-foreground shadow-sm">
          <LoaderCircleIcon className="size-4 animate-spin text-foreground" />
          Preparing your workspace access...
        </div>
      ) : null}
    </main>
  );
}

function WorkspaceOption({
  workspace,
  isBusy,
  onSelect,
}: {
  workspace: WorkspaceSummary;
  isBusy: boolean;
  onSelect: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onSelect}
      disabled={isBusy}
      className="flex w-full items-center justify-between gap-3 border border-border bg-background px-4 py-3 text-left transition-colors hover:bg-muted disabled:pointer-events-none disabled:opacity-60"
    >
      <div className="min-w-0">
        <p className="truncate text-sm font-medium text-foreground">
          {workspace.name}
        </p>
        <p className="truncate font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
          {workspace.slug}
        </p>
      </div>

      {isBusy ? (
        <LoaderCircleIcon className="size-4 animate-spin text-foreground" />
      ) : (
        <ArrowRightIcon className="size-4 text-muted-foreground" />
      )}
    </button>
  );
}

function appendNextPath(href: string, nextPath?: string) {
  if (!nextPath) return href;
  const separator = href.includes("?") ? "&" : "?";
  return `${href}${separator}next=${encodeURIComponent(nextPath)}`;
}

function getLastWorkspaceId(user: unknown) {
  if (!user || typeof user !== "object") return "";
  const value = (user as { lastWorkspaceId?: unknown }).lastWorkspaceId;
  return typeof value === "string" ? value : "";
}

export { WorkspaceSelector };
